### ISSUE TITLE
Promo codes activation API method

### ISSUE THREAD

**Issue by goforbroke1006** [goforbroke1006/ozon-api-stub#1]
You should implement logic for fake code activation and store history of codes activation (add new model with mongoose and write data to DB).
Appropriate test located in

> test/api/routes/partner-service/client-service.js:128

Case: if client activate code "SOMETEXT1900" then he got message "Code with discount 1900 was activated successfully" (last digits in code is value of fake code). In test I use random number. 

Example of response body you can found in

> api/routes/partner-service/client-service.js:52

PS. Sorry for my English.

**Comment by kugert** [comment]
Fake activation code service is done.
Method takes string -> cut discount amount from that string -> saves CodeName and DiscountValue.
